# Generated by Django 2.2.19 on 2021-03-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='phoneNo',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='postal_code',
            new_name='postalCode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referral_code',
        ),
        migrations.AddField(
            model_name='profile',
            name='oneSignalPlayerId',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='referralCode',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripeCustomerId',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
