# Generated by Django 2.2.27 on 2022-02-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_add_seedcustomers_to_domain1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_profile.profile',),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_profile.profile',),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_profile.profile',),
        ),
    ]
