export const TEST = 'TEST';

// AUTH
export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_UP = 'SIGN_UP';
export const DRIVER_SIGN_UP = 'DRIVER_SIGN_UP';
export const GET_DRIVER_SIGN_UP = 'GET_DRIVER_SIGN_UP';
export const DRIVER_SIGN_UP_SUCCESS = 'DRIVER_SIGN_UP_SUCCESS';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SOCIAL_SIGN_IN = 'SOCIAL_SIGN_IN';
export const SOCIAL_SIGN_IN_SUCCESS = 'SOCIAL_SIGN_IN_SUCCESS';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';

export const UPDATE_PLAYER_ID = 'UPDATE_PLAYER_ID';

//PRODUCT
export const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES';
export const FETCH_ALL_SERVICES = 'FETCH_ALL_SERVICES';
export const FETCH_ALL_CATEGORIES_SUCCESS = 'FETCH_ALL_CATEGORIES_SUCCESS';
export const FETCH_ALL_SERVICES_SUCCESS = 'FETCH_ALL_SERVICES_SUCCESS';
export const FETCH_ALL_FAQS = 'FETCH_ALL_FAQS';
export const FETCH_ALL_FAQS_SUCCESS = 'FETCH_ALL_FAQS_SUCCESS';
export const FETCH_FAQS_BY_ID = 'FETCH_FAQS_BY_ID';
export const FETCH_FAQS_BY_ID_SUCCESS = 'FETCH_FAQS_BY_ID_SUCCESS';

//LOV

export const FETCH_ALL_LOVS = 'FETCH_ALL_LOVS';
export const FETCH_ALL_LOVS_SUCCESS = 'FETCH_ALL_LOVS_SUCCESS';
export const SET_SYSTEM_CONFIG = 'SET_SYSTEM_CONFIG';
export const SET_TIME_SLOTS = 'SET_TIME_SLOTS';

// LOADER
export const LOADER = 'LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

//USER
export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
export const RESET_USER_PASSWORD = '  RESET_USER_PASSWORD';
export const FETCH_USER_PROFILE_SUCCESS = '  FETCH_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';

//ADDRESS
export const FETCH_USER_ADDRESS = 'FETCH_USER_ADDRESS';
export const UPDATE_USER_ADDRESS = 'UPDATE_USER_ADDRESS';
export const SAVE_USER_ADDRESS = 'SAVE_USER_ADDRESS';
export const FETCH_USER_ADDRESS_SUCCESS = 'FETCH_USER_ADDRESS_SUCCESS';
export const DELETE_USER_ADDRESS = 'DELETE_USER_ADDRESS';

//ORDER
export const PLACE_ORDER_DETAILS = 'PLACE_ORDER_DETAILS';
export const FETCH_ORDER_DETAILS = 'FETCH_ORDER_DETAILS';
export const FETCH_ALL_ORDERS = 'FETCH_ALL_ORDERS';
export const FETCH_ALL_ACTIVE_ORDERS = 'FETCH_ALL_ACTIVE_ORDERS';
export const FETCH_ORDER_HISTORY = 'FETCH_ORDER_HISTORY';
export const FETCH_ORDER_BY_ID = 'FETCH_ORDER_BY_ID';
export const SAVE_USER_ORDER = 'SAVE_USER_ORDER';
export const UPDATE_SAVED_USER_ORDER = 'UPDATE_SAVED_USER_ORDER';
export const FETCH_ALL_ORDERS_SUCCESS = 'FETCH_ALL_ORDERS_SUCCESS';
export const FETCH_ALL_ACTIVE_ORDERS_SUCCESS =
  'FETCH_ALL_ACTIVE_ORDERS_SUCCESS';
export const FETCH_ORDER_HISTORY_SUCCESS = 'FETCH_ORDER_HISTORY_SUCCESS';
export const FETCH_ORDER_BY_ID_SUCCESS = 'FETCH_ORDER_BY_ID_SUCCESS';
export const FETCH_ORDER_DETAILS_SUCCESS = 'FETCH_ORDER_DETAILS_SUCCESS';
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const MAKE_ORDER_PAYMENT = 'MAKE_ORDER_PAYMENT';
export const FETCH_ALL_DRIVER_TASKS = 'FETCH_ALL_DRIVER_TASKS';
export const FETCH_ALL_DRIVER_TASKS_SUCCESS = 'FETCH_ALL_DRIVER_TASKS_SUCCESS';
export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';
export const VALIDATE_ORDER_TIME_SLOT = 'VALIDATE_ORDER_TIME_SLOT';
export const NOTIFY_USER = 'NOTIFY_USER';

//COUPON
export const FETCH_ALL_COUPONS = 'FETCH_ALL_COUPONS';
export const FETCH_COUPON_BY_ID = 'FETCH_COUPON_BY_ID';
export const VALIDATE_COUPON = 'VALIDATE_COUPON';
export const FETCH_ALL_COUPONS_SUCCESS = 'FETCH_ALL_COUPONS_SUCCESS';
export const FETCH_COUPON_BY_ID_SUCCESS = 'FETCH_COUPON_BY_ID_SUCCESS';
export const VALIDATE_COUPON_SUCCESS = 'VALIDATE_COUPON_SUCCESS';
export const VALIDATE_COUPON_FAILED = 'VALIDATE_COUPON_FAILED';
export const VALIDATE_COUPON_REFFERAL = 'VALIDATE_COUPON_REFFERAL';
export const VALIDATE_COUPON_REFFERAL_SUCCESS =
  'VALIDATE_COUPON_REFFERAL_SUCCESS';
export const VALIDATE_COUPON_REFFERAL_FAILED =
  'VALIDATE_COUPON_REFFERAL_FAILED';

//PAYMENTS
export const FETCH_ALL_CARDS = 'FETCH_ALL_CARDS';
export const FETCH_ALL_CARDS_SUCCESS = 'FETCH_ALL_CARDS_SUCCESS';
export const DELETE_CARD = 'DELETE_CARD';
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS';
export const ADD_CARD = 'ADD_CARD';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';

export const DRIVER_SIGN_IN = 'DRIVER_SIGN_IN';
export const DRIVER_SIGN_IN_SUCCESS = 'DRIVER_SIGIN_IN_SUCCESS';
export const DRIVER_SIGN_IN_FAIL = 'DRIVER_SIGN_IN_FAIL';
