# Generated by Django 2.2.23 on 2021-06-06 07:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_category_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='startingFrom',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5),
        ),
    ]
