# Generated by Django 2.2.19 on 2021-03-24 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0002_auto_20210324_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('lng', models.CharField(blank=True, max_length=256)),
                ('lat', models.CharField(blank=True, max_length=256)),
                ('state', models.CharField(blank=True, max_length=256)),
                ('mainAddress', models.CharField(blank=True, max_length=256)),
                ('street', models.CharField(blank=True, max_length=256)),
                ('city', models.CharField(blank=True, max_length=256)),
                ('postalCode', models.CharField(blank=True, max_length=20)),
                ('buzzCode', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('suite', models.CharField(blank=True, default='', max_length=20)),
                ('address_type', models.CharField(blank=True, choices=[('residential', 'Residential')], default='residential', max_length=150, null=True)),
                ('isPrimary', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='user_profile.Profile')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
