# Generated by Django 2.2.20 on 2021-04-13 06:01

import core.utils
from django.conf import settings
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('logo', models.FileField(blank=True, default=None, null=True, upload_to=core.utils.media_directory)),
                ('typography', jsonfield.fields.JSONField(default=dict)),
                ('users', models.ManyToManyField(related_name='domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
