# Generated by Django 2.2.23 on 2021-06-01 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='site',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='sites.Site'),
        ),
    ]
