# Generated by Django 2.2.27 on 2022-02-03 08:32

import colorfield.fields
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_domain_deliveryfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='boxShadow',
            field=colorfield.fields.ColorField(default='#2c436a', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='domain',
            name='darkOrange',
            field=colorfield.fields.ColorField(default='#ED8F31', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='domain',
            name='fbBlue',
            field=colorfield.fields.ColorField(default='#255d9a', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='domain',
            name='fieldLabel',
            field=colorfield.fields.ColorField(default='#949EAE', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='domain',
            name='lightBlue',
            field=colorfield.fields.ColorField(default='#FC9834', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='domain',
            name='lightOrange',
            field=colorfield.fields.ColorField(default='#ed8f31', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='domain',
            name='steelBlue',
            field=colorfield.fields.ColorField(default='#2C436A', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='domain',
            name='white',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='domain',
            name='logo',
            field=models.FileField(blank=True, default='https://orange-voice-24288.s3.amazonaws.com/media/media_None/app_icon_big.png', null=True, upload_to=core.utils.media_directory),
        ),
    ]
