# Generated by Django 2.2.27 on 2022-02-06 08:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_auto_20220203_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='lightBlue',
        ),
        migrations.AlterField(
            model_name='domain',
            name='boxShadow',
            field=colorfield.fields.ColorField(default='#d4d6dc', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='domain',
            name='darkOrange',
            field=colorfield.fields.ColorField(default='#ED8F31', image_field=None, max_length=18, samples=None, verbose_name='Primary Dark'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='fbBlue',
            field=colorfield.fields.ColorField(default='#255d9a', image_field=None, max_length=18, samples=None, verbose_name='Facebook button'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='lightOrange',
            field=colorfield.fields.ColorField(default='#FC9834', image_field=None, max_length=18, samples=None, verbose_name='Primary Light'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='steelBlue',
            field=colorfield.fields.ColorField(default='#2C436A', image_field=None, max_length=18, samples=None, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='white',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Background'),
        ),
    ]
