# Generated by Django 2.2.20 on 2021-04-13 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
        ('voucher', '0002_auto_20210412_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='domain.Domain'),
        ),
    ]
