# Generated by Django 2.2.20 on 2021-04-09 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210326_0544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-modified_on',)},
        ),
    ]
