export const AuthTypes = {
    SIGNIN_PROG: 'SIGNIN_PROG',
    SIGNIN_SUCC: 'SIGNIN_SUCC',
    SIGNIN_FAIL: 'SIGNIN_FAIL',
    SET_USER: 'SET_USER',

    SIGNUP_PROG: 'SIGNUP_PROG',
    SIGNUP_SUCC: 'SIGNUP_SUCC',
    SIGNUP_FAIL: 'SIGNUP_FAIL',

    GET_NEW_ACCESS_TOKEN_PROG: 'GET_NEW_ACCESS_TOKEN_PROG',
    GET_NEW_ACCESS_TOKEN_SUCC: 'GET_NEW_ACCESS_TOKEN_SUCC',
    GET_NEW_ACCESS_TOKEN_FAIL: 'GET_NEW_ACCESS_TOKEN_FAIL',

    GET_ALL_USERS_PROG:'GET_ALL_USERS_PROG',
    GET_ALL_USERS_SUCC:'GET_ALL_USERS_SUCC',
    GET_ALL_USERS_FAIL:'GET_ALL_USERS_FAIL',

    CLEAR_ERROR: 'CLEAR_ERROR',

    SIGNOUT_USER: 'SIGNOUT_USER'
};