export const CategoryTypes = {
    GET_CATEGORIES_PROG: 'GET_CATEGORIES_PROG',
    GET_CATEGORIES_SUCC: 'GET_CATEGORIES_SUCC',
    GET_CATEGORIES_FAIL: 'GET_CATEGORIES_FAIL',


    ADD_CATEGORY_PROG: 'ADD_CATEGORY_PROG',
    ADD_CATEGORY_SUCC: 'ADD_CATEGORY_SUCC',
    ADD_CATEGORY_FAIL: 'ADD_CATEGORY_FAIL',

    EDIT_CATEGORY_PROG: 'EDIT_CATEGORY_PROG',
    EDIT_CATEGORY_SUCC: 'EDIT_CATEGORY_SUCC',
    EDIT_CATEGORY_FAIL: 'EDIT_CATEGORY_FAIL',


    DEL_CATEGORY_PROG: 'DEL_CATEGORY_PROG',
    DEL_CATEGORY_SUCC: 'DEL_CATEGORY_SUCC',
    DEL_CATEGORY_FAIL: 'DEL_CATEGORY_FAIL',

    TOGGLE_ADD_CATEGORY_MODAL: 'TOGGLE_ADD_CATEGORY_MODAL',
    TOGGLE_EDIT_CATEGORY_MODAL: 'TOGGLE_EDIT_CATEGORY_MODAL',
    TOGGLE_DEL_CATEGORY_MODAL: 'TOGGLE_DEL_CATEGORY_MODAL',



};