export const DomainTypes = {
  GET_DOMAIN_PROG: '@GET_DOMAIN_PROG',
  GET_DOMAIN_SUCC: '@GET_DOMAIN_SUCC',
  GET_DOMAIN_FAIL: '@GET_DOMAIN_FAIL',

  ADD_DOMAIN_PROG: 'ADD_DOMAIN_PROG',
  ADD_DOMAIN_SUCC: 'ADD_DOMAIN_SUCC',
  ADD_DOMAIN_FAIL: 'ADD_DOMAIN_FAIL', 
};
