export const DriverTypes = {
    GET_DRIVERS_PROG: 'GET_DRIVERS_PROG',
    GET_DRIVERS_SUCC: 'GET_DRIVERS_SUCC',
    GET_DRIVERS_FAIL: 'GET_DRIVERS_FAIL',


    GET_DRIVER_HISTORY_PROG: 'GET_DRIVER_HISTORY_PROG',
    GET_DRIVER_HISTORY_SUCC: 'GET_DRIVER_HISTORY_SUCC',
    GET_DRIVER_HISTORY_FAIL: 'GET_DRIVER_HISTORY_FAIL',

    ADD_DRIVER_PROG: 'ADD_DRIVER_PROG',
    ADD_DRIVER_SUCC: 'ADD_DRIVER_SUCC',
    ADD_DRIVER_FAIL: 'ADD_DRIVER_FAIL',

    EDIT_DRIVER_PROG: 'EDIT_DRIVER_PROG',
    EDIT_DRIVER_SUCC: 'EDIT_DRIVER_SUCC',
    EDIT_DRIVER_FAIL: 'EDIT_DRIVER_FAIL',


    DEL_DRIVER_PROG: 'DEL_DRIVER_PROG',
    DEL_DRIVER_SUCC: 'DEL_DRIVER_SUCC',
    DEL_DRIVER_FAIL: 'DEL_DRIVER_FAIL',

    TOGGLE_ADD_DRIVER_MODAL: 'TOGGLE_ADD_DRIVER_MODAL',
    TOGGLE_EDIT_DRIVER_MODAL: 'TOGGLE_EDIT_DRIVER_MODAL',
    TOGGLE_DEL_DRIVER_MODAL: 'TOGGLE_DEL_DRIVER_MODAL',



};