export const FaqTypes = {
    GET_FAQS_PROG: 'GET_FAQS_PROG',
    GET_FAQS_SUCC: 'GET_FAQS_SUCC',
    GET_FAQS_FAIL: 'GET_FAQS_FAIL',


    ADD_FAQ_PROG: 'ADD_FAQ_PROG',
    ADD_FAQ_SUCC: 'ADD_FAQ_SUCC',
    ADD_FAQ_FAIL: 'ADD_FAQ_FAIL',

    EDIT_FAQ_PROG: 'EDIT_FAQ_PROG',
    EDIT_FAQ_SUCC: 'EDIT_FAQ_SUCC',
    EDIT_FAQ_FAIL: 'EDIT_FAQ_FAIL',


    DEL_FAQ_PROG: 'DEL_FAQ_PROG',
    DEL_FAQ_SUCC: 'DEL_FAQ_SUCC',
    DEL_FAQ_FAIL: 'DEL_FAQ_FAIL',

    TOGGLE_ADD_FAQ_MODAL: 'TOGGLE_ADD_FAQ_MODAL',
    TOGGLE_EDIT_FAQ_MODAL: 'TOGGLE_EDIT_FAQ_MODAL',
    TOGGLE_DEL_FAQ_MODAL: 'TOGGLE_DEL_FAQ_MODAL',



};