export const LocationTypes = {
    GET_LOCATIONS_PROG: 'GET_LOCATIONS_PROG',
    GET_LOCATIONS_SUCC: 'GET_LOCATIONS_SUCC',
    GET_LOCATIONS_FAIL: 'GET_LOCATIONS_FAIL',


    ADD_LOCATION_PROG: 'ADD_LOCATION_PROG',
    ADD_LOCATION_SUCC: 'ADD_LOCATION_SUCC',
    ADD_LOCATION_FAIL: 'ADD_LOCATION_FAIL',

    EDIT_LOCATION_PROG: 'EDIT_LOCATION_PROG',
    EDIT_LOCATION_SUCC: 'EDIT_LOCATION_SUCC',
    EDIT_LOCATION_FAIL: 'EDIT_LOCATION_FAIL',


    DEL_LOCATION_PROG: 'DEL_LOCATION_PROG',
    DEL_LOCATION_SUCC: 'DEL_LOCATION_SUCC',
    DEL_LOCATION_FAIL: 'DEL_LOCATION_FAIL',

    TOGGLE_ADD_LOCATION_MODAL: 'TOGGLE_ADD_LOCATION_MODAL',
    TOGGLE_EDIT_LOCATION_MODAL: 'TOGGLE_EDIT_LOCATION_MODAL',
    TOGGLE_DEL_LOCATION_MODAL: 'TOGGLE_DEL_LOCATION_MODAL',



};