export const OrderTypes = {
    GET_ORDERS_PROG: 'GET_ORDERS_PROG',
    GET_ORDERS_SUCC: 'GET_ORDERS_SUCC',
    GET_ORDERS_FAIL: 'GET_ORDERS_FAIL',

    GET_ORDER_PROG: 'GET_ORDER_PROG',
    GET_ORDER_SUCC: 'GET_ORDER_SUCC',
    GET_ORDER_FAIL: 'GET_ORDER_FAIL',

    POST_ORDER_PROG: 'POST_ORDER_PROG',
    POST_ORDER_SUCC: 'POST_ORDER_SUCC',
    POST_ORDER_FAIL: 'POST_ORDER_FAIL',

    GET_CSV_DATA_PROG: 'GET_CSV_DATA_PROG',
    GET_CSV_DATA_SUCC: 'GET_CSV_DATA_SUCC',
    GET_CSV_DATA_FAIL: 'GET_CSV_DATA_FAIL',

    CLEAR_CSV_DATA: 'CLEAR_CSV_DATA',


    UPDATE_ORDER_STATUS_PROG: 'UPDATE_ORDER_STATUS_PROG',
    UPDATE_ORDER_STATUS_SUCC: 'UPDATE_ORDER_STATUS_SUCC',
    UPDATE_ORDER_STATUS_FAIL: 'UPDATE_ORDER_STATUS_FAIL',

    ADD_ORDER_PROG: 'ADD_ORDER_PROG',
    ADD_ORDER_SUCC: 'ADD_ORDER_SUCC',
    ADD_ORDER_FAIL: 'ADD_ORDER_FAIL',

    EDIT_ORDER_PROG: 'EDIT_ORDER_PROG',
    EDIT_ORDER_SUCC: 'EDIT_ORDER_SUCC',
    EDIT_ORDER_FAIL: 'EDIT_ORDER_FAIL',


    DEL_ORDER_PROG: 'DEL_ORDER_PROG',
    DEL_ORDER_SUCC: 'DEL_ORDER_SUCC',
    DEL_ORDER_FAIL: 'DEL_ORDER_FAIL',

    GET_LOV_PROG: 'GET_LOV_PROG',
    GET_LOV_SUCC: 'GET_LOV_SUCC',
    GET_LOV_FAIL: 'GET_LOV_FAIL',

    CANCEL_ORDER_PROG: 'CANCEL_ORDER_PROG',
    CANCEL_ORDER_SUCC: 'CANCEL_ORDER_SUCC',
    CANCEL_ORDER_FAIL: 'CANCEL_ORDER_FAIL',

    GET_ADDRESSES_PROG: 'GET_ADDRESSES_PROG',
    GET_ADDRESSES_SUCC: 'GET_ADDRESSES_SUCC',
    GET_ADDRESSES_FAIL: 'GET_ADDRESSES_FAIL',

    CHECK_SELECTED_PICKUP_SLOT_PROG: 'CHECK_SELECTED_PICKUP_SLOT_PROG',
    CHECK_SELECTED_PICKUP_SLOT_SUCC: 'CHECK_SELECTED_PICKUP_SLOT_SUCC',
    CHECK_SELECTED_PICKUP_SLOT_FAIL: 'CHECK_SELECTED_PICKUP_SLOT_FAIL',

    CHECK_SELECTED_DROPOFF_SLOT_PROG: 'CHECK_SELECTED_DROPOFF_SLOT_PROG',
    CHECK_SELECTED_DROPOFF_SLOT_SUCC: 'CHECK_SELECTED_DROPOFF_SLOT_SUCC',
    CHECK_SELECTED_DROPOFF_SLOT_FAIL: 'CHECK_SELECTED_DROPOFF_SLOT_FAIL',

    CLEAR_ERROR: 'CLEAR_ERROR',


    TOGGLE_ADD_ORDER_MODAL: 'TOGGLE_ADD_ORDER_MODAL',
    TOGGLE_STATUS_CONFIRMATION_MODAL: 'TOGGLE_STATUS_CONFIRMATION_MODAL',
    TOGGLE_EDIT_ORDER_MODAL: 'TOGGLE_EDIT_ORDER_MODAL',
    TOGGLE_DEL_ORDER_MODAL: 'TOGGLE_DEL_ORDER_MODAL',
    TOGGLE_PDF_ORDER_MODAL: 'TOGGLE_PDF_ORDER_MODAL',



};