export const ServiceTypes = {
    GET_SERVICES_PROG: 'GET_SERVICES_PROG',
    GET_SERVICES_SUCC: 'GET_SERVICES_SUCC',
    GET_SERVICES_FAIL: 'GET_SERVICES_FAIL',

    GET_SERVICES_BY_CATEGORY_PROG: 'GET_SERVICES_BY_CATEGORY_PROG',
    GET_SERVICES_BY_CATEGORY_SUCC: 'GET_SERVICES_BY_CATEGORY_SUCC',
    GET_SERVICES_BY_CATEGORY_FAIL: 'GET_SERVICES_BY_CATEGORY_FAIL',


    ADD_SERVICE_PROG: 'ADD_SERVICE_PROG',
    ADD_SERVICE_SUCC: 'ADD_SERVICE_SUCC',
    ADD_SERVICE_FAIL: 'ADD_SERVICE_FAIL',

    EDIT_SERVICE_PROG: 'EDIT_SERVICE_PROG',
    EDIT_SERVICE_SUCC: 'EDIT_SERVICE_SUCC',
    EDIT_SERVICE_FAIL: 'EDIT_SERVICE_FAIL',


    DEL_SERVICE_PROG: 'DEL_SERVICE_PROG',
    DEL_SERVICE_SUCC: 'DEL_SERVICE_SUCC',
    DEL_SERVICE_FAIL: 'DEL_SERVICE_FAIL',

    TOGGLE_DEL_SERVICE_MODAL: 'TOGGLE_DEL_SERVICE_MODAL',
    // TOGGLE_ADD_SERVICE_MODAL: 'TOGGLE_ADD_SERVICE_MODAL',
    // TOGGLE_EDIT_SERVICE_MODAL: 'TOGGLE_EDIT_SERVICE_MODAL',



};