export const TimeSlotTypes = {
  GET_TIME_SLOTS_PROG: 'GET_TIME_SLOTS_PROG',
  GET_TIME_SLOTS_SUCC: 'GET_TIME_SLOTS_SUCC',
  GET_TIME_SLOTS_FAIL: 'GET_TIME_SLOTS_FAIL',

  EDIT_TIME_SLOT_PROG: 'EDIT_TIME_SLOT_PROG',
  EDIT_TIME_SLOT_SUCC: 'EDIT_TIME_SLOT_SUCC',
  EDIT_TIME_SLOT_FAIL: 'EDIT_TIME_SLOT_FAIL',
};
