export const VoucherTypes = {
    GET_VOUCHERS_PROG: 'GET_VOUCHERS_PROG',
    GET_VOUCHERS_SUCC: 'GET_VOUCHERS_SUCC',
    GET_VOUCHERS_FAIL: 'GET_VOUCHERS_FAIL',


    ADD_VOUCHER_PROG: 'ADD_VOUCHER_PROG',
    ADD_VOUCHER_SUCC: 'ADD_VOUCHER_SUCC',
    ADD_VOUCHER_FAIL: 'ADD_VOUCHER_FAIL',

    EDIT_VOUCHER_PROG: 'EDIT_VOUCHER_PROG',
    EDIT_VOUCHER_SUCC: 'EDIT_VOUCHER_SUCC',
    EDIT_VOUCHER_FAIL: 'EDIT_VOUCHER_FAIL',


    DEL_VOUCHER_PROG: 'DEL_VOUCHER_PROG',
    DEL_VOUCHER_SUCC: 'DEL_VOUCHER_SUCC',
    DEL_VOUCHER_FAIL: 'DEL_VOUCHER_FAIL',

    TOGGLE_DEL_VOUCHER_MODAL: 'TOGGLE_DEL_VOUCHER_MODAL',
    // TOGGLE_ADD_VOUCHER_MODAL: 'TOGGLE_ADD_VOUCHER_MODAL',
    // TOGGLE_EDIT_VOUCHER_MODAL: 'TOGGLE_EDIT_VOUCHER_MODAL',



};