# Generated by Django 2.2.18 on 2021-02-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hello'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
