# Generated by Django 2.2.19 on 2021-03-23 14:04

from django.db import migrations, models
import driver.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('contactNumber', models.CharField(default='', max_length=20)),
                ('nationality', models.CharField(default='', max_length=200)),
                ('license', models.CharField(max_length=200)),
                ('lat', models.CharField(blank=True, default='', max_length=150)),
                ('lng', models.CharField(blank=True, default='', max_length=150)),
                ('mainAddress', models.TextField(default='')),
                ('avatar', models.FileField(blank=True, default=None, null=True, upload_to=driver.models.media_directory)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
