# Generated by Django 2.2.19 on 2021-03-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
