# Generated by Django 2.2.20 on 2021-04-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_driver_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='avatar',
            new_name='file',
        ),
    ]
