# Generated by Django 2.2.20 on 2021-04-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_auto_20210415_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='file',
            new_name='image',
        ),
    ]
